/** 
  implement a flexible structure, that allows any implemneting host to not change how their serialiser works... 
  Any addition to the container is a marker of this... 

  With modes the write sequence is changeable on load... and the quality is flexible.

  a tier contains with a canon the correct path to the localised, global, vendor, daw, user, plugins, assets, and resources....
*/
