/** 
  implement a flexible structure, that allows any implemneting host to not change how their serialiser works... 
  Any addition to the container is a marker of this... 

  With modes the write sequence is changeable on load... and the quality is flexible.

  a tier contains with a canon the correct path to the localised, global, vendor, daw, user, plugins, assets, and resources....

  a buffer can contain a tree ref, and loading recreates it fast... 
  a buffer can also be deep embedded paths with huge data...

  the container uses the tree to create tiers of a project at any branch...  these are merged or protected ( discouraged ) ... a common upper tree layer contains the paths for common paths so sub tree branch searching is reduced... 
*/
